development:
  adapter: postgresql
  database: private_events_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: private_events_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: private_events_production
  pool: 5
  timeout: 5000
